### ISSUE TITLE
Add ARM64 Support

### ISSUE THREAD

**Issue by XInTheDark** [Yetiowner/Increasing-code-complexity#13]
On Macs, the program is not optimized for the M1, M1 Pro, M1 Max, M1 Ultra, and M2 chips.
More information on Apple Silicon (from good, reliable Wikipedia):

Apple silicon is a series of [system on a chip](https://en.wikipedia.org/wiki/System_on_a_chip) (SoC) and [system in a package](https://en.wikipedia.org/wiki/System_in_package) (SiP) processors designed by [Apple Inc.](https://en.wikipedia.org/wiki/Apple_Inc.), mainly using the [ARM architecture](https://en.wikipedia.org/wiki/ARM_architecture). It is the basis of most new [Mac](https://en.wikipedia.org/wiki/Mac_(computer)) computers as well as [iPhone](https://en.wikipedia.org/wiki/IPhone), [iPad](https://en.wikipedia.org/wiki/IPad), [iPod Touch](https://en.wikipedia.org/wiki/IPod_Touch), [Apple TV](https://en.wikipedia.org/wiki/Apple_TV), and [Apple Watch](https://en.wikipedia.org/wiki/Apple_Watch), and of products such as [AirPods](https://en.wikipedia.org/wiki/AirPods), [HomePod](https://en.wikipedia.org/wiki/HomePod), [HomePod Mini](https://en.wikipedia.org/wiki/HomePod_Mini), and [AirTag](https://en.wikipedia.org/wiki/AirTag).

Apple announced its plan to [switch Mac computers from Intel processors](https://en.wikipedia.org/wiki/Mac_transition_to_Apple_silicon) to Apple silicon at [WWDC 2020](https://en.wikipedia.org/wiki/Apple_Worldwide_Developers_Conference#2020) on June 22, 2020.[[1]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-Apple_PR_2020.06.22-1)[[2]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-:1-2) The first Macs built with the [Apple M1](https://en.wikipedia.org/wiki/Apple_M1) processor were unveiled on November 10, 2020. In 2022, the newest Mac models have been built with Apple silicon; only older models of the [Mac Mini](https://en.wikipedia.org/wiki/Mac_Mini) and the [Mac Pro](https://en.wikipedia.org/wiki/Mac_Pro) still use [Intel Core](https://en.wikipedia.org/wiki/Intel_Core) and [Xeon](https://en.wikipedia.org/wiki/Xeon) processors respectively.[[3]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-3)[[4]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-4)

Apple fully controls the integration of Apple silicon chips with the company's hardware and software products. [Johny Srouji](https://en.wikipedia.org/wiki/Johny_Srouji) is in charge of Apple's silicon design.[[5]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-5) Manufacturing of the chips is outsourced to semiconductor contract manufacturers such as [Samsung](https://en.wikipedia.org/wiki/Samsung_Foundry) and [TSMC](https://en.wikipedia.org/wiki/TSMC).

The Apple "M" series is a family of [systems on a chip](https://en.wikipedia.org/wiki/System_on_a_chip) (SoC) used in [Mac computers](https://en.wikipedia.org/wiki/Macintosh) from November 2020 or later, [iPad Pro](https://en.wikipedia.org/wiki/IPad_Pro) tablets from April 2021 or later, and [iPad Air](https://en.wikipedia.org/wiki/IPad_Air) tablets from March 2022 or later. The "M" designation was previously used for [Apple motion coprocessors](https://en.wikipedia.org/wiki/Apple_motion_coprocessors).

Apple M1[[edit](https://en.wikipedia.org/w/index.php?title=Apple_silicon&action=edit&section=28)]
Main article: [Apple M1](https://en.wikipedia.org/wiki/Apple_M1)
Apple M1[[edit](https://en.wikipedia.org/w/index.php?title=Apple_silicon&action=edit&section=29)]
The M1, Apple's first system on a chip designed for use in Macs, is manufactured using [TSMC](https://en.wikipedia.org/wiki/TSMC)'s 5 nm process. Announced on November 10, 2020, it is used in the [MacBook Air](https://en.wikipedia.org/wiki/MacBook_Air_(Apple_silicon)) (M1, 2020), [Mac mini (M1, 2020)](https://en.wikipedia.org/wiki/Mac_Mini#Fifth_generation_(Apple_silicon)), [MacBook Pro (13-inch, M1, 2020)](https://en.wikipedia.org/wiki/MacBook_Pro#4th_generation_(Apple_Silicon)), [iMac](https://en.wikipedia.org/wiki/IMac_(Apple_silicon)) (24-inch, M1, 2021), [iPad Pro (5th generation)](https://en.wikipedia.org/wiki/IPad_Pro_(5th_generation)) and [iPad Air (5th generation)](https://en.wikipedia.org/wiki/IPad_Air_(5th_generation)). It comes with 4 performance cores and 4 efficiency cores, for a total of 8 CPU cores. It comes with up to 8 GPU cores, with the entry level MacBook Air having only 7 GPU cores. The M1 has 16 billion transistors.[[168]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-178)

Apple M1 Pro[[edit](https://en.wikipedia.org/w/index.php?title=Apple_silicon&action=edit&section=30)]
The M1 Pro is a more powerful version of the M1, with six to eight performance cores, two efficiency cores, 14 to 16 GPU cores, 16 Neural Engine cores, up to 32 GB unified RAM with up to 200 GB/s memory bandwidth, and more than double the transistors. It was announced on October 18, 2021, and is used in the 14- and 16-inch [MacBook Pro](https://en.wikipedia.org/wiki/MacBook_Pro). Apple said the CPU performance is about 70% faster than the M1, and that its GPU performance is about double. Apple claims the M1 Pro can deliver up to 20 streams of 4K or 7 streams of 8K ProRes video playback (up from 6 offered by Afterburner card for [2019 Mac Pro](https://en.wikipedia.org/wiki/Mac_Pro#3rd_generation_(Lattice_Tower_or_Rack))).

Apple M1 Max[[edit](https://en.wikipedia.org/w/index.php?title=Apple_silicon&action=edit&section=31)]
The M1 Max is a larger version of the M1 Pro chip, with eight performance cores, two efficiency cores, 24 to 32 GPU cores, 16 Neural Engine cores, up to 64 GB unified RAM with up to 400 GB/s memory bandwidth, and more than double the number of transistors. It was announced on October 18, 2021, and is used in the 14- and 16-inch [MacBook Pro](https://en.wikipedia.org/wiki/MacBook_Pro), as well as the [Mac Studio](https://en.wikipedia.org/wiki/Mac_Studio). Apple says it has 57 billion transistors.[[169]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-179) Apple claims the M1 Max can deliver up to 30 streams of 4K (up from 23 offered by Afterburner card for 2019 Mac Pro) or 7 streams of 8K ProRes video playback.

Apple M1 Ultra[[edit](https://en.wikipedia.org/w/index.php?title=Apple_silicon&action=edit&section=32)]
The M1 Ultra consists of two M1 Max dies connected together by a silicon interposer through Apple's UltraFusion technology.[[170]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-180) It has 114 billion transistors, 16 performance cores, 4 efficiency cores, 48 to 64 GPU cores and 32 Neural Engine cores; it can be configured with up to 128 GB unified RAM of 800 GB/s memory bandwidth. It was announced on March 8, 2022, as an optional upgrade for the [Mac Studio](https://en.wikipedia.org/wiki/Mac_Studio). Apple claims the M1 Ultra can deliver up to 18 streams of 8K ProRes video playback.[[171]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-181)

Apple M2[[edit](https://en.wikipedia.org/w/index.php?title=Apple_silicon&action=edit&section=33)]
Main article: [Apple M2](https://en.wikipedia.org/wiki/Apple_M2)
Apple announced the M2 SoC on June 6, 2022, at [WWDC](https://en.wikipedia.org/wiki/WWDC), along with the new MacBook Air and the new 13-inch MacBook Pro. It is the successor to the Apple M1. The M2 is made with TSMC's "Enhanced 5-nanometer technology" N5P process and contains 20 billion transistors, a 25% increase from the previous generation M1. The M2 can be configured with up to 24 gigabytes of RAM and 2 terabytes of storage. It has 8 CPU cores (4 performance and 4 efficiency) and up to 10 GPU cores. The M2 also increases the memory bandwidth to 100 GB/s. Apple claims CPU improvements up to 18% and GPU improvements up to 35% compared to the previous M1.[[172]](https://en.wikipedia.org/wiki/Apple_silicon#cite_note-182)

We should optimise for ARM64 architectures.

**Comment by Yetiowner** [comment]
No
