### ISSUE TITLE
Android 13 Support

### ISSUE THREAD

**Issue by Wave6677** [Yetiowner/Increasing-code-complexity#5]
This software doesn't work on Android 13 yet. Can it be ported?

**Comment by TheSamDickey** [comment]
Perhaps we can just use rust to convert this to web assembly. After confirming the migration works using regression testing, we can circle back to shifting into a SSR SPA design that takes advantage of react native for android 13 support.  In this phase it is crucial we maximize performance by confirming all asynchronous external calls are done in a concurrent, simultaneous batch. It would be advantageous to bring on a UI and UX team to rapidly drive users onto the platform. I also cannot stress the importance of SEO enough, if our CTR is below the linear median of our stakeholders, then we will struggle to provide a coherent, forward-thinking, iterative application.

**Comment by TheSamDickey** [comment]
(I'm just memeing around, if any future employer is reading this as an evaluation of my knowledge/competence)
